AM request container and submit a cmd to run in the container.
Exception when connecting to Node Manager:

13/10/07 22:27:57 ERROR security.UserGroupInformation: PriviledgedActionException
as:shzhao (auth:SIMPLE) cause:java.io.IOException:
org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN]

Signed-off-by: Shanyu Zhao <shzhao@microsoft.com>